#myName = input("What's you name?: ")
#myAge = input("How old are you? :")
#print("Gee, that's REALLY OLD")
#replit = input("Do you like Replit?")
#print("OF COURSE YOU DO!")

#print()
#print("So, you are")
#print(myName)
#print("and are the ripe old age of")
#print(myAge)
#print("and clearly think that Replit is")
#print(replit)

#variable = input("WHO GOES THERE? ")
#print(variable)

#myGrandma = input("How's your Grandma doing? 😘 ")
#print(myGrandma)

#myLunch = input("What are you having for lunch? ")
#print("Hmm, it sounds like you really should just order")
#print(myLunch)
#print("as soon as possible!")

#print("Definitely not a Phishing Scam")
#print()
#myName= input("Your Name  ")
#print("Thanks for logging in")
#print(myName)
#cardNumber = input("What is your credit card number?  ")
#print("Thanks, I definitely wont put")
#print(cardNumber)
#print("into Amazon and order anything weird")
#print()
#print("Promise")
#maidenName= input("What is your Mother's maiden name? ")
#print()
#print("That's cool, I just wanted to know that")
#print(maidenName)
#print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

print("""Hi there, thank you for joining ThinkAlike! In order to 
find some kindred spirits please fill in the following 
info:""")
UserName= input("Name:  ")
FavFood= input("Favourite food:  ")
FavMusic= input("Favourite song:  ")
Home= input("Closest city of residence:  ")

print("Thanks for signing up and completing your profile key info!")
print(UserName)
print("Look for finding more people who love eating  ")
print(FavFood)
print("and who listen to  ")
print(FavMusic)
print("on repeat!")
